import { Injectable, UnauthorizedException, BadRequestException, InternalServerErrorException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { PrismaService } from '../prisma/prisma.service';
import * as bcrypt from 'bcrypt';
import { LoginDto } from './dto/login.dto';
import { RegisterDto } from './dto/register.dto';

@Injectable()
export class AuthService {
    constructor(
        private prisma: PrismaService,
        private jwtService: JwtService,
    ) { }

    async validateUser(email: string, pass: string): Promise<any> {
        const user = await this.prisma.user.findUnique({ where: { email } });
        if (user && (await bcrypt.compare(pass, user.password))) {
            const { password, ...result } = user;
            return result;
        }
        return null;
    }

    async login(loginDto: LoginDto) {
        const user = await this.validateUser(loginDto.email, loginDto.password);
        if (!user) {
            throw new UnauthorizedException('Invalid credentials');
        }
        const payload = { email: user.email, sub: user.id, role: user.role };
        return {
            access_token: this.jwtService.sign(payload),
            user: payload,
        };
    }

    async register(registerDto: RegisterDto) {
        try {
            const hashedPassword = await bcrypt.hash(registerDto.password, 10);
            const user = await this.prisma.user.create({
                data: {
                    email: registerDto.email,
                    password: hashedPassword,
                    role: registerDto.role,
                    // Auto-trim trailing spaces generated by mobile autocorrect
                    branchId: registerDto.branchId?.trim(),
                },
            });
            const { password, ...result } = user;
            return result;
        } catch (error: any) {
            if (error.code === 'P2002') {
                throw new BadRequestException('Email is already registered!');
            }
            if (error.code === 'P2003') {
                throw new BadRequestException('Invalid Branch ID. Please check and try again.');
            }
            throw new InternalServerErrorException('Server Error: Ensure the Branch ID is a valid system ID.');
        }
    }
}
